#!/bin/bash

# VERIFICARE COMPILARE SI RULARE PROGRAM

if [[ -z "$1" ]]
then
    echo "Eroare: Te rog specifica numele directorului temei."
    echo "Utilizare: $0 <nume_director_tema>"
    exit 1
fi

TEMA_DIR="$1"

if [[ ! -d "$TEMA_DIR" ]]
then
    echo "Eroare: Directorul specificat '$TEMA_DIR' nu exista."
    exit 1
fi

cd "$TEMA_DIR"

echo " "
echo " "

# Compilare proiect
g++ -o my_program sources/*.cpp -Iheaders 2> compile_errors.txt

if [[ $? -ne 0 ]]
then
    echo "Eroare: Compilarea a esuat. Verifica erorile de mai jos:"
    cat compile_errors.txt
    exit 1
fi

# Rulare program
./my_program > run_output.txt 2> run_errors.txt

if [[ $? -ne 0 ]]
then
    echo "Eroare: Programul a intampinat erori in timpul rularii. Verifica erorile de mai jos:"
    cat run_errors.txt
    exit 1
fi

if [[ $(grep -i "warning" compile_errors.txt) ]]
then
    echo "Avertizare: Au existat warning-uri in timpul compilarii. Verifica warning-urile de mai jos:"
    cat compile_errors.txt
    exit 1
fi

echo "Succes: Programul a fost compilat si rulat fara erori sau warning-uri."
cat run_output.txt

rm compile_errors.txt run_output.txt run_errors.txt

echo " "
echo " "

# AFISARE CLASE

cd headers

# Cautare clase in headers
nr_cls=0
echo "Clasele definite in cadrul temei sunt:"
for file in *.h
do
    echo "In fișierul: $file"
    egrep "^class" $file | cut -f2 -d" "
    echo "-----------------------"
    let nr_cls=nr_cls+1
done

echo "Numarul total de clase:" $nr_cls

echo " "
echo " "

# DIAGRAMA

echo "Diagrama simplificata a claselor:"

for file in *.h
do
    echo "Fișierul: $file"
    line=`egrep "^class" $file`
    class=`echo $line | cut -f2 -d" "`
    inh=`echo $line | cut -f2- -d: | sed 's/^[[:space:]]*//'`
    public=`echo $inh | cut -f1 -d" "`
    result=`echo $inh | sed 's/public\s*//g'`
    echo "  Class: $class"
        if [[ "$public" == "public" ]]
        then
            echo "    Inherits from: $result"
        fi
        
    echo "-----------------------"
done

echo " "
echo " "

# FUNCTIILE DIN FIECARE CLASA

echo "Functiile implementate in fiecare clasa:"
for file in *.h
do
    echo "Fișierul: $file"
    line=`egrep "^class" $file`
    class=`echo $line | cut -f2 -d" "`
    echo "  Class: $class"
    
    func=`cat $file | egrep ".+);$|override;$|0;$"`
    
    echo "$func"

done

echo " "
echo " "

# INTERFETE

echo "In cadrul programului exista urmatoarele interfete:"

nr_int=0
int_list=""
for file in *.h
do
    class=`cat $file | egrep "^class" | cut -f2 -d" "`
    total=`cat $file | egrep ".+;$" | head -n -1 | wc -l`
    virtual=`cat $file | egrep ".+0;$" | wc -l`
    let dif=total-virtual
    if [[ $dif -eq 0 && $virtual -ne 0 ]]
    then
    	int_list+="$class "
    	let nr_int=nr_int+1
    fi
done

echo $int_list

echo " "
echo " "

# CLASE ABSTRACTE

echo "In cadrul programului exista urmatoarele clase abstracte:"

for c in $int_list
do
virt_list=""
    cc=${c}.h
    while read line
    do
    	virtual=`echo $line | egrep ".+0;$"`
    	if [[ ! -z $virtual ]]
    	then
            clean_line=$(echo "$virtual" | sed 's/virtual //' | sed 's/ = 0//')
    	    virt_list+="$clean_line "
    	fi
    done < $cc
    for file in *.h
    do
    	if [[ $file != $cc ]]
    	then
            ver=`cat $file | egrep "^class" | egrep "$c"`
        if [[ ! -z $ver ]]
        then
            ok=0
            for v in $virt_list
            do
                verr=`cat $file | egrep "$v"`
                if [[ ! -z $verr ]]
                then
                    virt_list=$(echo "$virt_list" | sed 's/$v//g')
                    ok=1
                fi
            done
            if [[ $ok -eq 1 ]]
            then 
            	abs=$(echo $file | sed 's/\.h$//')
            	abs_list+="$abs"
            fi
        fi
        fi
    done
done

echo $abs_list

